PITCH_LENGTH = 105.0
PITCH_WIDTH = 68.0
PITCH_HALF_LENGTH = PITCH_LENGTH * 0.5
PITCH_HALF_WIDTH = PITCH_WIDTH * 0.5
PITCH_MARGIN = 5.0

END_LINE_RIGHT_TEAM = PITCH_LENGTH / 2
END_LINE_LEFT_TEAM = -END_LINE_RIGHT_TEAM
OUT_LINE_RIGHT = PITCH_WIDTH / 2
OUT_LINE_LEFT = -OUT_LINE_RIGHT

CENTER_CIRCLE_R = 9.15

PENALTY_AREA_LENGTH = 16.5
PENALTY_AREA_WIDTH = 40.32
PENALTY_CIRCLE_R = 9.15
PENALTY_SPOT_DIST = 11.0

GOAL_WIDTH = 14.02
GOAL_HALF_WIDTH = GOAL_WIDTH * 0.5
GOAL_AREA_LENGTH = 5.5
GOAL_AREA_WIDTH = 18.32
GOAL_DEPTH = 2.44
GOAL_POST_RADIUS = 0.06

CORNER_ARC_R = 1.0
